; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev_ota

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    miq19/eModbus@^1.7.4
    bodmer/TFT_eSPI
    knolleary/PubSubClient@^2.8

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_MISO=-1
    -D TFT_DC=27
    -D TFT_RST=26
    -D TFT_CS=25
    -D TOUCH_CS=-1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_OFF
    -D SPI_FREQUENCY=20000000
    -D USE_HSPI_PORT
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D LOAD_GFXFF
    -D SMOOTH_FONT
    -D MQTT_MAX_PACKET_SIZE=1024

lib_ignore =
    ESPAsyncTCP

[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_protocol = espota
upload_port = 192.168.0.250

upload_flags =
    --auth=HJfq-sdZf9-A23hO13k

lib_deps =
    miq19/eModbus@^1.7.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    bodmer/TFT_eSPI
    knolleary/PubSubClient@^2.8

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_MISO=-1
    -D TFT_DC=27
    -D TFT_RST=26
    -D TFT_CS=25
    -D TOUCH_CS=-1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_OFF
    -D SPI_FREQUENCY=20000000
    -D USE_HSPI_PORT
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D LOAD_GFXFF
    -D SMOOTH_FONT
    -D MQTT_MAX_PACKET_SIZE=1024
